language: node_js
node_js:
  - "6"
install: npm install
sudo: required
addons:
  apt:
    packages:
      - sshpass
script: node testbuild.js
after_success:
  - sshpass -p $PASSWORD scp -o stricthostkeychecking=no -r guide $USER@104.236.130.43:/home/deploy