language: node_js
node_js:
  - "6"
install: npm install
sudo: required
after_success:
   - "sudo apt-get install sshpass"
   - "sshpass -p $FTP_PASSWORD scp -r ./public $FTP_USER@104.236.130.43:/home/deploy/dist"