language: node_js
node_js:
  - "6"
install: npm install
sudo: required
addons:
  apt:
    packages:
      - sshpass
after_success:
  - export SSHPASS=$PASS
  - scp -o stricthostkeychecking=no -r public $USER@104.236.130.43:/home/deploy/dist