language: node_js
node_js:
  - "6"
install: npm install
sudo: required
addons:
  apt:
    packages:
      - sshpass
after_success:
  - "export SSHPASS=$PASSWORD"
  - "sshpass -e scp -r public $USER@104.236.130.43:/home/deploy/dist"